language: python

python:
  - 3.6

services: mysql

env:
  - DJANGO=1.11.4

before_install:
  - export DJANGO_SETTINGS_MODULE=fairuze.test
  - export PYTHONPATH=$HOME/builds/ahmedaljazzar/fairuze
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

before_script:
  - mysql -e 'CREATE DATABASE fairuze DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'

script:
  - python manage.py test
  - prospector
