# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.Track'),
        ),
    ]
