# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_polymorphism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(related_name='artists', related_query_name='artist', to='song.Song'),
        ),
        migrations.RemoveField(
            model_name='composer',
            name='songs',
        ),
        migrations.AddField(
            model_name='composer',
            name='songs',
            field=models.ManyToManyField(related_name='composers', related_query_name='composer', to='song.Song'),
        ),
        migrations.RemoveField(
            model_name='writer',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='writer',
            name='lyrics',
            field=models.ManyToManyField(related_name='writers', related_query_name='writer', to='song.Lyric'),
        ),
    ]
