# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=75, null=True)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
