# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_contactrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='last_name',
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
