# Generated by Django 2.1.3 on 2018-11-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20170825_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='song',
            name='track',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='lyrics',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Composer',
        ),
        migrations.DeleteModel(
            name='Lyric',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
