# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20170825_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='song',
            name='track',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='track',
            name='info',
        ),
        migrations.AddField(
            model_name='lyric',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Track'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Composer',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.AddField(
            model_name='lyric',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='songs.Person'),
        ),
        migrations.AddField(
            model_name='lyric',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composer', to='songs.Person'),
        ),
        migrations.AddField(
            model_name='lyric',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='songs.Person'),
        ),
    ]
