# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20171117_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/people'),
        ),
    ]
