# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='songs.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people'),
        ),
    ]
