# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20171117_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Remove', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Remove', max_length=50),
            preserve_default=False,
        ),
    ]
