# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20171117_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
