# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_person_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
