# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20171117_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
