# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_auto_20171117_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
