# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_auto_20171119_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='person',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='people'),
        ),
    ]
